# Uncomment the next line to define a global platform for your project
inhibit_all_warnings!
platform :ios, '12.0'

def pods
  use_frameworks!
  # RX
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'NSObject+Rx'
end

target 'gs_rxswift' do
  # Comment the next line if you don't want to use dynamic frameworks
  pods
end
